#!/usr/bin/python3
import sys
import os

os.chdir('./statements/latex')

listFiles = []

if len(sys.argv) == 1:
    listFiles = os.listdir('.')
else:
    for i in range(1, len(sys.argv)):
        listFiles.append(sys.argv[i])

print(listFiles)



for data in listFiles:
    name = ''
    if data.endswith('.tex'):
        name = data[:4]
    else:
        continue
    if os.path.exists('{}.tex'.format(name)):
        os.system('xelatex -interaction=batchmode {}.tex'.format(name))

    extension = ["{}.aux", "{}.fls", "{}.log", "{}.out", "{}.fdb_latexmk", "{}.synctex.gz"]

    for ext in extension:
        if os.path.exists(ext.format(name)):
            os.remove(ext.format(name))

    if os.path.exists('__latexindent_temp.tex'):
        os.remove('__latexindent_temp.tex')


    if os.path.exists('{}.pdf'.format(name)):
        os.replace('{}.pdf'.format(name), '../pdf/{}.pdf'.format(name))
    else:
        print("Failed to generate pdf")

os.chdir('../../')